In [2]:
import os
os.getcwd()

'/Users/ruthmengesha'

In [3]:
os.listdir()

['Untitled7.ipynb',
 '.config',
 'Music',
 'SQL settings',
 '.condarc',
 '.docker',
 'Untitled5.ipynb',
 'Untitled1.ipynb',
 '.DS_Store',
 'binary_patients',
 '.CFUserTextEncoding',
 'wekafiles',
 '.xonshrc',
 'patientsheetsample.xml',
 'anaconda_projects',
 'Untitled3.ipynb',
 'module 3',
 'Untitled.ipynb',
 '.zshrc',
 'Untitled4.ipynb',
 '.local',
 '.psql_history',
 'Untitled6.ipynb',
 'Pictures',
 'Postman',
 'projectpt3.ipynb',
 '.zsh_history',
 'Untitled2.ipynb',
 '.ipython',
 'Desktop',
 'Library',
 '.matplotlib',
 'HI720_Project.ipynb',
 '.lesshst',
 'hi719_assignment.py',
 '.pgadmin',
 '.lemminx',
 'SQLQuery_2.sql',
 'Module6Assignment1Q2.R',
 'Public',
 'joined_data_module3',
 '.tcshrc',
 'joined data',
 '.virtual_documents',
 '.anaconda',
 'Untitled8.ipynb',
 'Movies',
 'Applications',
 '.Rapp.history',
 '.Trash',
 'defaultSettings.json',
 '.ipynb_checkpoints',
 '.jupyter',
 'Documents',
 '.azuredatastudio',
 '.vscode',
 'hi720_claims_dgn_demo_distorted.csv',
 '.bash_profile',
 'Downloads',
 '.continuum',
 'seer_claims_matched_records.csv',
 'Untitled9.ipynb',
 '.zsh_sessions',
 '.conda',
 'ngram_results.rds',
 'hi720_seer_distorted.csv']

In [6]:
df = pd.read_csv("~/Downloads/KaggleV2-May-2016.csv")

In [7]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [8]:
# rename columns for consistency
df.rename(columns={
    'No-show': 'No_Show',
    'Hipertension': 'Hypertension',
    'Handcap': 'Handicap'
}, inplace=True)

# convert target variable to numeric (Yes=1, No=0)
df['no_show'] = df['no_show'].map({'Yes': 1, 'No': 0})

df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,hypertension,Diabetes,Alcoholism,handicap,SMS_received,no_show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,0
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,0
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,0
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,0
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,0

In [9]:
df.drop(['PatientId', 'AppointmentID', 'Neighbourhood'], axis=1, inplace=True)

In [10]:
# convert to datetime
df['ScheduledDay'] = pd.to_datetime(df['ScheduledDay'])
df['AppointmentDay'] = pd.to_datetime(df['AppointmentDay'])

# create new feature: wait time
df['days_wait'] = (df['AppointmentDay'] - df['ScheduledDay']).dt.days

In [11]:
df['Gender'] = df['Gender'].map({'F': 0, 'M': 1})

In [12]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Gender          110527 non-null  int64
 1   ScheduledDay    110527 non-null  datetime64[ns, UTC]
 2   AppointmentDay  110527 non-null  datetime64[ns, UTC]
 3   Age             110527 non-null  int64
 4   Scholarship     110527 non-null  int64
 5   hypertension    110527 non-null  int64
 6   Diabetes        110527 non-null  int64
 7   Alcoholism      110527 non-null  int64
 8   handicap        110527 non-null  int64
 9   SMS_received    110527 non-null  int64
 10  no_show         110527 non-null  int64
 11  days_wait       110527 non-null  int64
dtypes: datetime64[ns, UTC](2), int64(10)
memory usage: 10.1 MB

In [13]:
df.drop(['ScheduledDay', 'AppointmentDay'], axis=1, inplace=True)

In [14]:
from sklearn.model_selection import train_test_split

# define features (X) and target (y)
X = df.drop('no_show', axis=1)   # or 'No_Show' if that's what you used
y = df['no_show']

# split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

X_train.shape, X_test.shape

((88421, 9), (22106, 9))

In [18]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)
y_prob_lr = lr.predict_proba(X_test)[:,1]

In [19]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)
y_prob_dt = dt.predict_proba(X_test)[:,1]

In [20]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)
y_prob_rf = rf.predict_proba(X_test)[:,1]

In [21]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score

def evaluate_model(y_true, y_pred, y_prob, model_name):
    print(f"{model_name}")
    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("Precision:", precision_score(y_true, y_pred))
    print("Recall:", recall_score(y_true, y_pred))
    print("AUC-ROC:", roc_auc_score(y_true, y_prob))
    print("-" * 30)

evaluate_model(y_test, y_pred_lr, y_prob_lr, "Logistic Regression")
evaluate_model(y_test, y_pred_dt, y_prob_dt, "Decision Tree")
evaluate_model(y_test, y_pred_rf, y_prob_rf, "Random Forest")

Logistic Regression
Accuracy: 0.7955306251696372
Precision: 0.3526315789473684
Recall: 0.015008960573476702
AUC-ROC: 0.6632095611584281
------------------------------
Decision Tree
Accuracy: 0.7671672849000272
Precision: 0.35596794601433995
Recall: 0.18906810035842295
AUC-ROC: 0.5947383892970466
------------------------------
Random Forest
Accuracy: 0.7640459603727495
Precision: 0.3562691131498471
Recall: 0.20878136200716846
AUC-ROC: 0.6681740208178674
------------------------------

In [22]:
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(rf, X, y, cv=5, scoring='roc_auc')
cv_scores.mean()

np.float64(0.6512112936234328)

In [23]:
rf = RandomForestClassifier(class_weight='balanced', random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)
y_prob_rf = rf.predict_proba(X_test)[:,1]

evaluate_model(y_test, y_pred_rf, y_prob_rf, "Random Forest (Balanced)")

Random Forest (Balanced)
Accuracy: 0.6969601013299557
Precision: 0.3129080863887494
Recall: 0.41868279569892475
AUC-ROC: 0.6394261449034745
------------------------------

In [24]:
df.head()

,Gender,Age,Scholarship,hypertension,Diabetes,Alcoholism,handicap,SMS_received,no_show,days_wait
0,0,62,0,1,0,0,0,0,0,-1
1,1,56,0,0,0,0,0,0,0,-1
2,0,62,0,0,0,0,0,0,0,-1
3,0,8,0,0,0,0,0,0,0,-1
4,0,56,0,1,1,0,0,0,0,-1

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Gender        110527 non-null  int64
 1   Age           110527 non-null  int64
 2   Scholarship   110527 non-null  int64
 3   hypertension  110527 non-null  int64
 4   Diabetes      110527 non-null  int64
 5   Alcoholism    110527 non-null  int64
 6   handicap      110527 non-null  int64
 7   SMS_received  110527 non-null  int64
 8   no_show       110527 non-null  int64
 9   days_wait     110527 non-null  int64
dtypes: int64(10)
memory usage: 8.4 MB

In [26]:
df['days_wait'] = (df['AppointmentDay'] - df['ScheduledDay']).dt.days

KeyError: 'AppointmentDay'

In [27]:
cv_scores.mean()

np.float64(0.6512112936234328)